# Generated by Django 5.2.10 on 2026-07-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company_placementdrive_application'),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='recruiters.recruiterprofile'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to='recruiters.recruiterprofile'),
        ),
    ]
