# Generated by Django 5.2.10 on 2026-07-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('placement_officer', 'Placement Officer')], default='student', max_length=25),
        ),
    ]
