# Generated by Django 5.2.10 on 2026-07-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placement', '0002_company_placementdrive_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('Technical', 'Technical'), ('HR', 'HR'), ('Managerial', 'Managerial')], max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('interviewer', models.CharField(max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placement.application')),
            ],
        ),
    ]
